version: "3.9"

services:

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: windmill-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    container_name: windmill-client
    ports:
      - "80:80"
    restart: always