// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Services;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(WindmillDbContext))]
    [Migration("20260312080312_ChangedUser")]
    partial class ChangedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Entities.Commands", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("args")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("issuedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Server.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Entities.WindmillAlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Server.Entities.WindmillTelemetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("ambientTemperatur")
                        .HasColumnType("real");

                    b.Property<float>("bladePitch")
                        .HasColumnType("real");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("gearboxTemp")
                        .HasColumnType("real");

                    b.Property<float>("generatorTemp")
                        .HasColumnType("real");

                    b.Property<float>("nacelleDirection")
                        .HasColumnType("real");

                    b.Property<float>("powerOutput")
                        .HasColumnType("real");

                    b.Property<float>("rotorSpeed")
                        .HasColumnType("real");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("turbineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("vibration")
                        .HasColumnType("real");

                    b.Property<float>("windDirection")
                        .HasColumnType("real");

                    b.Property<float>("windSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
